change bash to sh change timeout judgement change syncFail judgement init excutable added synclog added

diff --git a/templates/_basicTemplate b/templates/_basicTemplate
--- a/templates/_basicTemplate
+++ b/templates/_basicTemplate
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 filename=`basename $0`
 
 # create the lock
@@ -44,16 +44,26 @@ fi
 # before sync comands here <--------------------------------------------------------
 
 # sync
+startSyncTime=$(date +%s)
+set -o pipefail
 echo '==== sync '$filename' start ===='
-timeout %(timeout)% %(synctool)% # enter the sync command here <--------------------
+timeout --preserve-status %(timeout)%h %(synctool)%        | tee %(logpath)%/${filename}"_"$(date +%F_%T)".log"
+                                                  #  ^^^^<---enter the sync command here <-----------
+result=$?
+stopSyncTime=$(date+%s)
 
-if [ $? -eq 124 ]
+if [ $((stopSyncTime-startSyncTime)) -gt $((%(timeout)%*3600)) ]
 then
-	#sync timeout
 	echo -e $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
 else
-	#sync succeeded
-	echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	if [ $result -eq 0 ]	#<------ modify success critirea here <-------------------
+	then
+		#sync succeeded
+		echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	else
+		#sync failed
+		echo -e $filename"\tfailed\t"$(date +%F_%T) >> %(syncLog)%
+	fi
 fi
 
 # after sync commands here <-------------------------------------------------------
diff --git a/templates/gitTemplate b/templates/gitTemplate
--- a/templates/gitTemplate
+++ b/templates/gitTemplate
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 filename=`basename $0`
 
 # create the lock
@@ -43,6 +43,8 @@ fi
 
 
 # sync
+startSyncTime=$(date +%s)
+set -o pipefail
 echo '==== sync '$filename' start ===='
 if [ ! -d %(syncpath)% ]
 then
@@ -51,17 +53,25 @@ fi
 
 currentPath=$PWD
 cd %(syncpath)%
-timeout %(timeout)% %(synctool)% %(parameter)%
-isTimeout=$?
+timeout --preserve-status %(timeout)%h %(synctool)% %(parameter)% | tee %(logPath)%/${filename}"_"$(date +%F_%T)".log"
+result=$?
 cd $currentPath
 
-if [ $isTimeout -eq 124 ]
+stopSyncTime=$(date +%s)
+
+if [ $((startSyncTime-stopSyncTime)) -gt $((%(timeout)%*3600)) ]
 then
 	#sync timeout
 	echo -e $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
 else
-	#sync succeeded
-	echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	if [ $result -eq 0 ]
+	then
+		#sync succeeded
+		echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	else
+		#sync failed
+		echo -e $filename"\tfailed\t"$(date +%F_%T) >> %(syncLog)%
+	fi
 fi
 
 echo '==== sync '$filename' stop ===='
diff --git a/templates/lftpTemplate b/templates/lftpTemplate
--- a/templates/lftpTemplate
+++ b/templates/lftpTemplate
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 filename=`basename $0`
 
 # create the lock
@@ -29,21 +29,32 @@ then
 fi
 
 # sync
+startSyncTime=$(date +%s)
+set -o pipefail
 echo '==== sync '$filename' start ===='
 
 currentPath=$PWD
 cd %(syncPath)%
-timeout %(timeout)% %(synctool)% "%(url)%" -e "mirror --verbose -P %(threads)% --delete; bye"
+timeout --preserve-status %(timeout)%h %(synctool)% "%(url)%" -e "mirror --verbose -P %(threads)% --delete; bye" | tee %(logPath)%/${filename}"_"$(date +%F_%T)".log"
 result=$?
 cd $currentPath
 
-if [ $result -eq 124 ]
+stopSyncTime=$(date +%s)
+
+if [ $((stopSyncTime-startSyncTime)) -gt %((%(timeout)%*3600)) ]
 then
 	#sync timeout
 	echo -e $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
 else
-	#sync succeeded
-	echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	if [ $result -eq 0 ]
+	then
+		#sync succeeded
+		echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	else
+		#sync failed
+		echo -e $filename"\tfailed\t"$(date +%F_%T) >> %(syncLog)%
+	fi
+		
 fi
 
 # after sync commands here <-------------------------------------------------------
diff --git a/templates/rsyncTemplate b/templates/rsyncTemplate
--- a/templates/rsyncTemplate
+++ b/templates/rsyncTemplate
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 filename=`basename $0`
 
 # create the lock
@@ -24,16 +24,27 @@ fi
 echo $filename >> _syncLock
 
 # sync
+startSyncTime=$(date +%s)
+set -o pipefail
 echo '==== sync '$filename' start ===='
-timeout %(timeout)% %(syncTool)% %(parameter)% %(url)% %(syncPath)%
+timeout --preserve-status  %(timeout)%h %(syncTool)% %(parameter)% %(url)% %(syncPath)% | tee %(logPath)%/${filename}"_"$(date +%F_%T)".log"
+result=$?
 
-if [ $? -eq 124 ]
+stopSyncTime=$(date +%s)
+
+if [ $((stopSyncTime-startSyncTime)) -gt $((%(timeout)%*3600)) ]
 then
 	#sync timeout
 	echo -e $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
 else
-	#sync succeeded
-	echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	if [ $result -eq 0 ]
+	then
+		#sync succeeded
+		echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
+	else
+		#sync failed
+		echo -e $filename"\tfailed\t"$(date +%F_%T) >> %(syncLog)%
+	fi
 fi
 
 echo '==== sync '$filename' stop ===='
